name = "apil"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "f42839cf-67f4-426f-a69e-9e40ad28d85f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
